elixir-for-programmers/gallows/lib/gallows_web/router.ex
defmodule GallowsWeb.Router do
  use GallowsWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/hangman", GallowsWeb do
    pipe_through :browser  # use the default browser stack

    get "/", HangmanController, :new_game
    post "/", HangmanController, :create_game
    put "/", HangmanController, :make_move
  end

  # Other scopes may use custom stacks.
  # scope "/api", GallowsWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: GallowsWeb.Telemetry
    end
  end
end

elixir-for-programmers/gallows/lib/gallows/application.ex
defmodule Gallows.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    children = [
      # Start the Telemetry supervisor
      GallowsWeb.Telemetry,
      # Start the PubSub system
      {Phoenix.PubSub, name: Gallows.PubSub},
      # Start the Endpoint (http/https)
      GallowsWeb.Endpoint
      # Start a worker by calling: Gallows.Worker.start_link(arg)
      # {Gallows.Worker, arg}
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Gallows.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    GallowsWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

elixir-for-programmers/gallows/lib/gallows_web/controllers/hangman_controller.ex
defmodule GallowsWeb.HangmanController do
  use GallowsWeb, :controller

  def new_game(conn, _params) do
    render(conn, "new_game.html")
  end

  def create_game(conn, _params) do
    game = Hangman.new_game()
    tally = Hangman.tally(game)
    my_assigns = %{tally: tally}
    conn
    |> put_session(:game, game)
    |> render("game_field.html", my_assigns)
  end

  def make_move(conn, params) do
    # raise inspect(params)  # use this to see in the browser what params contains
    guess = params["make_move"]["guess"]
    tally = 
        conn
        |> get_session(:game)
        |> Hangman.make_move(guess)
    put_in(conn.params["make_move"]["guess"], "")
    |> render("game_field.html", tally: tally)
  end
end

elixir-for-programmers/gallows/lib/gallows_web/views/error_view.ex
defmodule GallowsWeb.ErrorView do
  use GallowsWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

elixir-for-programmers/gallows/lib/gallows_web/views/hangman_view.ex
defmodule GallowsWeb.HangmanView do
  use GallowsWeb, :view

  def word_so_far(tally) do
    tally.revealed |> Enum.join(" ")
  end

end

elixir-for-programmers/gallows/lib/gallows_web/views/layout_view.ex
defmodule GallowsWeb.LayoutView do
  use GallowsWeb, :view
end

elixir-for-programmers/gallows/lib/gallows_web/templates/hangman/game_field.html.eex
<%= inspect(@tally) %>

<p>
Turns left: <%= @tally.turns_left %>
</p>

<p>
Word so far: <%= word_so_far(@tally) %>
</p>

<%= form_for(@conn, Routes.hangman_path(@conn, :make_move), [as: :make_move, method: :put], fn form -> %>
    <%= text_input(form, :guess) %>
    <% submit("Make next move") %>
<% end) %>
</form>

elixir-for-programmers/gallows/lib/gallows_web/templates/hangman/new_game.html.eex
<h1>Welcome to Hangman!</h1>

<%= button("New Game", to: Routes.hangman_path(@conn, :create_game)) %>

elixir-for-programmers/gallows/lib/gallows_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Hello Hangman</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= @inner_content %>
    </main>
  </body>
</html>